# Generated by Django 4.1.5 on 2023-05-12 04:14

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios_tentativos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100)),
                ('codigo_validacion', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
